// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: args.proto

package mypb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ArgsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N int32 `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	M int32 `protobuf:"varint,2,opt,name=m,proto3" json:"m,omitempty"`
}

func (x *ArgsReq) Reset() {
	*x = ArgsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_args_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArgsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArgsReq) ProtoMessage() {}

func (x *ArgsReq) ProtoReflect() protoreflect.Message {
	mi := &file_args_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArgsReq.ProtoReflect.Descriptor instead.
func (*ArgsReq) Descriptor() ([]byte, []int) {
	return file_args_proto_rawDescGZIP(), []int{0}
}

func (x *ArgsReq) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *ArgsReq) GetM() int32 {
	if x != nil {
		return x.M
	}
	return 0
}

type ArgsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reply int32 `protobuf:"varint,1,opt,name=reply,proto3" json:"reply,omitempty"`
}

func (x *ArgsResp) Reset() {
	*x = ArgsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_args_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArgsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArgsResp) ProtoMessage() {}

func (x *ArgsResp) ProtoReflect() protoreflect.Message {
	mi := &file_args_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArgsResp.ProtoReflect.Descriptor instead.
func (*ArgsResp) Descriptor() ([]byte, []int) {
	return file_args_proto_rawDescGZIP(), []int{1}
}

func (x *ArgsResp) GetReply() int32 {
	if x != nil {
		return x.Reply
	}
	return 0
}

var File_args_proto protoreflect.FileDescriptor

var file_args_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x61, 0x72, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x07,
	0x41, 0x72, 0x67, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x01, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x6d, 0x22, 0x20, 0x0a, 0x08, 0x41, 0x72, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x72, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x2e, 0x0a, 0x0b, 0x41, 0x72, 0x67, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x08, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79,
	0x12, 0x08, 0x2e, 0x41, 0x72, 0x67, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x41, 0x72, 0x67,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x6d, 0x79, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_args_proto_rawDescOnce sync.Once
	file_args_proto_rawDescData = file_args_proto_rawDesc
)

func file_args_proto_rawDescGZIP() []byte {
	file_args_proto_rawDescOnce.Do(func() {
		file_args_proto_rawDescData = protoimpl.X.CompressGZIP(file_args_proto_rawDescData)
	})
	return file_args_proto_rawDescData
}

var file_args_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_args_proto_goTypes = []interface{}{
	(*ArgsReq)(nil),  // 0: ArgsReq
	(*ArgsResp)(nil), // 1: ArgsResp
}
var file_args_proto_depIdxs = []int32{
	0, // 0: ArgsService.multiply:input_type -> ArgsReq
	1, // 1: ArgsService.multiply:output_type -> ArgsResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_args_proto_init() }
func file_args_proto_init() {
	if File_args_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_args_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArgsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_args_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArgsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_args_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_args_proto_goTypes,
		DependencyIndexes: file_args_proto_depIdxs,
		MessageInfos:      file_args_proto_msgTypes,
	}.Build()
	File_args_proto = out.File
	file_args_proto_rawDesc = nil
	file_args_proto_goTypes = nil
	file_args_proto_depIdxs = nil
}
